/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxiSwing;


import javax.swing.JOptionPane;
import taxi.DAO.taxiDAO;
import taxi.metier.taxi;

/**
 *
 * @author camma
 */
public class creaTaxi extends javax.swing.JPanel {

    taxiDAO taxiDAO = null;

    public creaTaxi() {
        initComponents();
    }

    public void setTaxiDAO(taxiDAO taxiDAO) {
        this.taxiDAO = taxiDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        immat = new javax.swing.JLabel();
        carburant = new javax.swing.JLabel();
        prixkm = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        txtImmatriculation = new javax.swing.JTextField();
        txtCarburant = new javax.swing.JTextField();
        txtPrixkm = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        buttonCreer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumTaxi = new javax.swing.JTextField();

        immat.setText("Immatriculation");

        carburant.setText("Carburant");

        prixkm.setText("Prix au km");

        description.setText("Description");

        txtImmatriculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImmatriculationActionPerformed(evt);
            }
        });

        txtCarburant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarburantActionPerformed(evt);
            }
        });

        txtPrixkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixkmActionPerformed(evt);
            }
        });

        buttonCreer.setText("Créer");
        buttonCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreerActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero du taxi");

        txtNumTaxi.setEditable(false);
        txtNumTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTaxiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(immat)
                    .addComponent(description)
                    .addComponent(prixkm)
                    .addComponent(carburant)
                    .addComponent(jLabel1))
                .addGap(65, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCreer)
                    .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtPrixkm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCarburant, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtImmatriculation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumTaxi))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(immat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carburant)
                    .addComponent(txtCarburant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrixkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prixkm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(buttonCreer)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtImmatriculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImmatriculationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImmatriculationActionPerformed

    private void txtCarburantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarburantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarburantActionPerformed

    private void txtPrixkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixkmActionPerformed

    private void buttonCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreerActionPerformed

        try {
            String immatriculation = txtImmatriculation.getText();
            String carburant = txtCarburant.getText();
            int prixkm = Integer.parseInt(txtPrixkm.getText());
            String description = txtDescription.getText();

            taxi tx = new taxi(0, immatriculation, carburant, prixkm, description);
            tx = taxiDAO.create(tx);
            txtNumTaxi.setText("" + tx.getIdtaxi());
            JOptionPane.showMessageDialog(this, "Taxi créé ! ", "succès", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buttonCreerActionPerformed

    private void txtNumTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTaxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTaxiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreer;
    private javax.swing.JLabel carburant;
    private javax.swing.JLabel description;
    private javax.swing.JLabel immat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel prixkm;
    private javax.swing.JTextField txtCarburant;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtImmatriculation;
    private javax.swing.JTextField txtNumTaxi;
    private javax.swing.JTextField txtPrixkm;
    // End of variables declaration//GEN-END:variables
}
