/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxiSwing;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import taxi.DAO.locationDAO;
import taxi.metier.location;
import taxi.DAO.taxiDAO;

/**
 *
 * @author camma
 */
public class TaxiLocation extends javax.swing.JPanel {

    locationDAO locationDAO = null;
    taxiDAO taxiDAO = null;
    
    DefaultTableModel dft1 = new DefaultTableModel();
    
    public TaxiLocation() {
        initComponents();
        dft1.addColumn("ID loc");
        dft1.addColumn("Date loc");
        dft1.addColumn("KM total");
        dft1.addColumn("Acompte");
        dft1.addColumn("Total");
        dft1.addColumn("ID cli");
        dft1.addColumn("ID taxi");
        dft1.addColumn("ID adr deb");
        dft1.addColumn("ID adr fin");
        jTable1.setModel(dft1);
    }
    
    public void setLocationDAO(locationDAO locationDAO) {
        this.locationDAO = locationDAO;
    }
    
    public void setTaxiDAO(taxiDAO taxiDAO) {
        this.taxiDAO = taxiDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idtaxi = new javax.swing.JLabel();
        txtIdtaxi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        idtaxi.setText("ID du taxi recherché :");

        txtIdtaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdtaxiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(idtaxi)
                .addGap(48, 48, 48)
                .addComponent(txtIdtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtaxi)
                    .addComponent(txtIdtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdtaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdtaxiActionPerformed
        try {

            int idtaxi = Integer.parseInt(txtIdtaxi.getText());
            List<location> listLoc = taxiDAO.rechLoc(idtaxi);
            int nr = dft1.getRowCount();
            for (int i = nr - 1; i >= 0; i--) {
                dft1.removeRow(i);
            }
            for (location loc : listLoc) {
                Vector v = new Vector();
                v.add(loc.getIdLoc());
                v.add(loc.getDateLoc());
                v.add(loc.getKmtotal());
                v.add(loc.getAcompte());
                v.add(loc.getTotal());
                v.add(loc.getIdClient());
                v.add(loc.getIdTaxi());
                v.add(loc.getIdAdrDebut());
                v.add(loc.getIdAdrFin());
                dft1.addRow(v);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "L'ID est introuvable.", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtIdtaxiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idtaxi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIdtaxi;
    // End of variables declaration//GEN-END:variables
}
